[features]
seeds = false
skip-lint = false

[programs.localnet]
basic_oracle = "AbvSo2Z6qtAy6Z6rytQG1k4H9pKrJ7NS5ur3tVkA5TeM"
twap_oracle = "3NKUtPKboaQN4MwY3nyULBesFaW7hHsXFrBTVjbn2nBr"
task_runner_oracle = "C4cm9mYew1kS6N6woKquiVs1TUUEgvbHm5fm9985oM7v"

[programs.devnet]
basic_oracle = "AbvSo2Z6qtAy6Z6rytQG1k4H9pKrJ7NS5ur3tVkA5TeM"
twap_oracle = "3NKUtPKboaQN4MwY3nyULBesFaW7hHsXFrBTVjbn2nBr"
task_runner_oracle = "C4cm9mYew1kS6N6woKquiVs1TUUEgvbHm5fm9985oM7v"

[provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

cluster = "Devnet"
wallet = "~/.config/solana/id.json"
# wallet = "~/switchboard_environments_v2/devnet/upgrade_authority/upgrade_authority.json"

# cluster = "Mainnet"
# wallet = "~/switchboard_environments_v2/mainnet/upgrade_authority/upgrade_authority.json"


[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-basic-oracle = "tsx ./scripts/init-basic-oracle.ts"
watch = "tsx ./scripts/watch.ts"

