[features]
seeds = false
skip-lint = false

[programs.localnet]
basic_oracle = "3NKUtPKboaQN4MwY3nyULBesFaW7hHsXFrBTVjbn2nBr"
task_runner_oracle = "dvBPs44kNgw6k2or4qpoAoPgct5nbEwqrD5VDRGfifd"

[programs.devnet]
basic_oracle = "3NKUtPKboaQN4MwY3nyULBesFaW7hHsXFrBTVjbn2nBr"
task_runner_oracle = "dvBPs44kNgw6k2or4qpoAoPgct5nbEwqrD5VDRGfifd"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/task_runner_oracle.ts"
init = "tsx ./scripts/initialize.ts"
watch = "tsx ./scripts/watch.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[test]
startup_wait = 15000

[[test.validator.clone]] # sb devnet oracle programID
address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"

[[test.validator.clone]] # sb devnet oracle IDL
address = "Fi8vncGpNKbq62gPo56G4toCehWNy77GgqGkTaAF5Lkk"

[[test.validator.clone]] # sb devnet oracle SbState
address = "CyZuD7RPDcrqCGbNvLCyqk6Py9cEZTKmNKujfPi3ynDd"

[[test.validator.clone]] # sb devnet oracle tokenVault
address = "7hkp1xfPBcD2t1vZMoWWQPzipHVcXeLAAaiGXdPSfDie"

[[test.validator.clone]] # sb devnet attestation programID
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

[[test.validator.clone]] # sb devnet attestation IDL
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"

[[test.validator.clone]] # sb devnet attestation State
address = "5MFs7RGTjLi1wtKNBFRtuLipCkkjs4YQwRRU9sjnbQbS"
