[features]
seeds = false
skip-lint = false

[programs.localnet]
BASICORACLE = "BCJATkVR9bV7XCHR9drRwusbm4CfG13rpwrtEfNfnicm"
srfx_usdc_oracle = "BCJATkVR9bV7XCHR9drRwusbm4CfG13rpwrtEfNfnicm"
task_runner_oracle = "FAqBpxJsdsAntjDv9iAb3WwL2F7PYaJLbm5B97kgbNep"

[programs.devnet]
BASICORACLE = "BCJATkVR9bV7XCHR9drRwusbm4CfG13rpwrtEfNfnicm"
srfx_usdc_oracle = "BCJATkVR9bV7XCHR9drRwusbm4CfG13rpwrtEfNfnicm"
task_runner_oracle = "FAqBpxJsdsAntjDv9iAb3WwL2F7PYaJLbm5B97kgbNep"

[provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

cluster = "Devnet"
wallet = "~/.config/solana/id.json"
# wallet = "~/switchboard_environments_v2/devnet/upgrade_authority/upgrade_authority.json"

# cluster = "Mainnet"
# wallet = "~/switchboard_environments_v2/mainnet/upgrade_authority/upgrade_authority.json"


[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-basic-oracle = "tsx ./scripts/init-basic-oracle.ts"
watch = "tsx ./scripts/watch.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[test]
startup_wait = 15000

[[test.validator.clone]] # sb devnet oracle programID
address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"

[[test.validator.clone]] # sb devnet oracle IDL
address = "Fi8vncGpNKbq62gPo56G4toCehWNy77GgqGkTaAF5Lkk"

[[test.validator.clone]] # sb devnet oracle SbState
address = "CyZuD7RPDcrqCGbNvLCyqk6Py9cEZTKmNKujfPi3ynDd"

[[test.validator.clone]] # sb devnet oracle tokenVault
address = "7hkp1xfPBcD2t1vZMoWWQPzipHVcXeLAAaiGXdPSfDie"

[[test.validator.clone]] # sb devnet attestation programID
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

[[test.validator.clone]] # sb devnet attestation IDL
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"

[[test.validator.clone]] # sb devnet attestation State
address = "5MFs7RGTjLi1wtKNBFRtuLipCkkjs4YQwRRU9sjnbQbS"
